### ISSUE TITLE
§ilk §wap grant application

### ISSUE THREAD

**Issue by zenopie** [securesecrets/ShadeGrants#3]
# Silk Swap Team

## Project Description
This is an application for a grant for silk swap:

We intend to create a swap on Secret Network. Use of this swap will increase the capital efficiency of Shade Protocol and enable feeless swaps of protocol necessary components

Our team has been closely following Ethereum DeFi and Secret Network in the last year, and are active in the chat channels. Needless to say, we are really excited to see this project evolve.

## Problem / Solution
Swap fees create a capital inefficiency in maintaining the silk peg by arbitrage

## Detailed product description
<img width="1124" alt="silkswapV2" src="https://user-images.githubusercontent.com/3359350/164134610-93e25fe1-8176-4452-8243-2a268d37e58f.png">

![Weekly buy proposal](https://user-images.githubusercontent.com/3359350/164157739-beed83e0-3913-44c4-b0f4-16c87af1cad4.png)
 proposal type for weekly liquidity buys and monthly LP allocations

## Go-to-Market plan
smoke weed everyday

## Value capture for Shade ecosystem
The main KPIs for Shade Protocol is TVL, feeless swaps for protocol components and a revenue stream to the main treasury

## Team members
* Braydn Larsen (zenopie)
* your mom
* your dad

## Team Website	
* https://www.youtube.com/watch?v=PIb6AZdTr-A

## Team's experience
* cleaning toilets
* wiping up shit
* dusting

## Team Code Repos
* https://github.com/zenopie/EarthNetwork
* https://github.com/zenopie/HumanityDAO
* https://github.com/zenopie/AnimalSwap

## Development Roadmap
We will require 3 months to complete this project. We intend to have 2 developers full-time and 1 part-time with unknown costs to human spirit and body

Example milestones:
* Implement treasury (weeks 0 - 4).
* Implement pairs (weeks 4 - 8).
* Implement proposals (weeks 8 - 12).

Ideally, we can receive payments in 3 disbursements, one at the beginning of the grant, one after implementation of pairs and last payment when the development work is completed.

I would like to be paid $250,000 in shade through a 3 year linearly unlocked staking contract with the ability to change my staking risk level and claim staking rewards

**Comment by CarterLWoetzel** [comment]
This is a giga-brain proposal, feel free to ping me directly on discord for next steps. The go-to-market plan and team experience drives a signifcant amount of confidence, and this proposal is truly the gold standard from here on out!

**Comment by zenopie** [comment]
thank you! exited to move forward
